### ISSUE TITLE
Any official support plan for ros2ci from OSRF?

### ISSUE THREAD

**Issue by JaehyunShim** [mikaelarguedas/ros2ci#25]
Hi, 

As the title says, do OSRF have any plans for official ros2ci support?
I can see a repository for [docker images](https://github.com/osrf/docker_images) but nothing for ros2ci. 

Thanks! 
Ryan

**Comment by mikaelarguedas** [comment]
Hi Ryan,

OSRF's currently provides CI support via the `dev` and `PR` jobs on the ROS (1 and 2) buildfarms: http://wiki.ros.org/buildfarm/Pull%20request%20testing.
To my knowledge all the other ROS (2) CI solutions are community efforts. So the short answer is no.

---

This repo was created to try to fill a gap for people wanting to host a CI solution on their repository as opposed to on the ROS buildfarm. There are now multiple other maintained CI solutions with ROS2 support, although the main use case I had for it was to be able to run CI against ROS2 nightly builds that was (and maybe still is) not very well supported by other solutions. 

Some of the other ROS2 CI solutions:
- [industrial_ci](https://github.com/ros-industrial/industrial_ci/) (mostly to test against released distributions although support for nightly builds is [limited but possible](https://github.com/mikaelarguedas/sros2/blob/106f31e949ed847bb12115f72b2942aa26443ea2/.github/workflows/ici.yml#L11))
- [action-ros-ci](https://github.com/ros-tooling/action-ros-ci/) (for building all from sources)

The docker images can also be used to have more control over what happens in your CI. An example of workflow using them is available [here](https://github.com/ros2/sros2/blob/219dd9fbd7d27b55e131648eb2408a50859983d4/.github/workflows/test.yml#L1)
I've been trying to contribute to these CI projects in order to consolidate existing solutions and render this `ros2ci` repository obsolete.

**Comment by JaehyunShim** [comment]
@mikaelarguedas 

Thank you very much for the comment. I tested the second one (action-ros-ci) in my personal repository and it worked perfectly fine.
I will check if we can switch our team open-source projects from the previous method to the new one. 

Thank you for your help and have a good day. 
Ryan
