### ISSUE TITLE
Build additional repos in underlay workspace

### ISSUE THREAD

**Issue by mikaelarguedas** [mikaelarguedas/ros2ci#4]
currently "additional repos" are built along the repo using the CI.
They should be in an underlay workspace, built first, not tested and then sourced before building and testing the overlay

**Comment by mikaelarguedas** [comment]
Addressed in https://github.com/mikaelarguedas/ros2ci/pull/9

**Comment by Karsten1987** [comment]
maybe I did something wrong here, but I am not sure if that problem is fully addressed.

e.g.: https://travis-ci.org/ros-drivers/urg_node/jobs/640114300?utm_medium=notification&utm_source=github_status

I am building `urg_node` with `urg_c` as a dependency. `urg_c` was never released, but specified in the `additional_repos.repos` file. Yet, the build fails because it's trying to look up rosdep keys for `urg_c`.

**Comment by mikaelarguedas** [comment]
Yeah the issue is in the travis file, posted [this comment](https://github.com/ros-drivers/urg_node/pull/50/commits/b3e5ea37b4b51069d2d03a29dbcf9b95179dd0ff#r369246696) for more details
